# frozen_string_literal: true

module S4C
  # Emits SUBNEG4 assembly text compatible with the subneg4-vue parser.
  #
  # Output format:
  #   - Data section: label:value lines (one per line)
  #   - Code section: A, B, C, D lines (comma-separated operands)
  #   - Labels: label: prefix on instruction/data lines
  #   - Comments: // text
  class Emitter
    def initialize(memory, instructions, show_result: false)
      @mem = memory
      @instructions = instructions
      @show_result = show_result
    end

    def emit
      lines = []

      # Header comment
      lines << "// Generated by s4c (LLVM IR → SUBNEG4 compiler)"
      lines << ""

      # Data section
      lines << "// === Data Section ==="
      @mem.data_entries.each do |label, value|
        lines << "#{label}:#{value}"
      end
      lines << ""

      # Code section
      lines << "// === Code Section ==="
      pending_labels = []

      @instructions.each do |inst|
        case inst
        when Array
          type = inst[0]
          case type
          when :label
            name, comment = inst[1], inst[2]
            if name && !name.empty?
              pending_labels << name
            end
            lines << "// #{comment}" if comment && !comment.empty?
          when :data
            name, value, comment = inst[1], inst[2], inst[3]
            cmt = comment && !comment.empty? ? " // #{comment}" : ""
            lines << "#{name}:#{value}#{cmt}"
          when :comment
            lines << "// #{inst[1]}"
          end
        when Subneg4
          # Prepend any pending labels
          prefix = ""
          unless pending_labels.empty?
            prefix = pending_labels.map { |l| "#{l}:" }.join
            pending_labels.clear
          end
          cmt = inst.comment && !inst.comment.empty? ? " // #{inst.comment}" : ""
          lines << "#{prefix}#{inst.a}, #{inst.b}, #{inst.c}, #{inst.d}#{cmt}"
        end
      end

      # Flush any remaining pending labels (shouldn't happen normally)
      pending_labels.each do |l|
        lines << "#{l}:0"
      end

      # Optional output directive for return value
      if @show_result && @mem.data_entries.any? { |l, _| l == "v___retval" }
        lines << ""
        lines << ">>> Result: ${v___retval()}"
      end

      lines.join("\n") + "\n"
    end
  end
end
