# frozen_string_literal: true

module S4C
  # Emits SUBNEG4 assembly text compatible with the subneg4-vue parser.
  class Emitter
    def initialize(memory, instructions, show_result: false)
      @mem = memory
      @instructions = instructions
      @show_result = show_result
    end

    def emit
      lines = []

      lines << "// Generated by s4c (LLVM IR → SUBNEG4 compiler)"
      lines << ""

      # Data section
      lines << "// === Data Section ==="
      @mem.data_entries.each do |label, value|
        if label == "__stack_SP"
          lines << "#{label}:&stack_top"
        elsif @mem.addr_of_refs[label]
          lines << "#{label}:&#{@mem.addr_of_refs[label]}"
        else
          lines << "#{label}:#{value}"
        end
      end
      lines << ""

      # Code section
      lines << "// === Code Section ==="
      pending_labels = []

      @instructions.each do |inst|
        case inst
        when Array
          type = inst[0]
          case type
          when :label
            name, comment = inst[1], inst[2]
            if name && !name.empty?
              pending_labels << name
            end
            lines << "// #{comment}" if comment && !comment.empty?
          when :data
            name, value, comment = inst[1], inst[2], inst[3]
            cmt = comment && !comment.empty? ? " // #{comment}" : ""
            lines << "#{name}:#{value}#{cmt}"
          when :comment
            lines << "// #{inst[1]}"
          when :addr_data
            # Data word with &label (address-of) as value
            name, label, comment = inst[1], inst[2], inst[3]
            cmt = comment && !comment.empty? ? " // #{comment}" : ""
            lines << "#{name}:&#{label}#{cmt}"
          when :return_jump
            # Self-modifying goto: cd:D_LABEL: A, B, C, 0
            _, a, b, c, d_label, comment = inst
            prefix = flush_labels(pending_labels)
            cmt = comment && !comment.empty? ? " // #{comment}" : ""
            lines << "#{prefix}#{a}, #{b}, #{c}, cd:#{d_label}:0#{cmt}"
          when :push_write
            # Self-modifying write: A, B, cc:C_LABEL:0, NEXT
            _, a, b, c_label, comment = inst
            prefix = flush_labels(pending_labels)
            cmt = comment && !comment.empty? ? " // #{comment}" : ""
            lines << "#{prefix}#{a}, #{b}, cc:#{c_label}:0, NEXT#{cmt}"
          when :pop_read
            # Self-modifying read: A, cb:B_LABEL:0, C, NEXT
            _, a, b_label, c, comment = inst
            prefix = flush_labels(pending_labels)
            cmt = comment && !comment.empty? ? " // #{comment}" : ""
            lines << "#{prefix}#{a}, cb:#{b_label}:0, #{c}, NEXT#{cmt}"
          end
        when Subneg4
          prefix = flush_labels(pending_labels)
          cmt = inst.comment && !inst.comment.empty? ? " // #{inst.comment}" : ""
          lines << "#{prefix}#{inst.a}, #{inst.b}, #{inst.c}, #{inst.d}#{cmt}"
        end
      end

      # Flush any remaining pending labels
      pending_labels.each do |l|
        lines << "#{l}:0"
      end

      # Find main's return value variable
      retval_label = @mem.data_entries.map(&:first).find { |l| l == "main___retval" }
      retval_label ||= @mem.data_entries.map(&:first).find { |l| l.end_with?("___retval") }
      if @show_result && retval_label
        lines << ""
        lines << ">>> Result: ${#{retval_label}()}"
      end

      # Stack allocation (if stack is used)
      sp_label = @mem.data_entries.map(&:first).find { |l| l == "__stack_SP" }
      if sp_label
        lines << ""
        lines << "// === Stack ==="
        lines << "\#{#{STACK_SIZE}, stack_bottom, stack_top}#"
      end

      lines.join("\n") + "\n"
    end

    STACK_SIZE = 4096

    private

    def flush_labels(pending_labels)
      return "" if pending_labels.empty?
      prefix = pending_labels.map { |l| "#{l}:" }.join
      pending_labels.clear
      prefix
    end
  end
end
