# frozen_string_literal: true

require 'set'

module S4C
  # Emits SUBNEG4 assembly text compatible with the subneg4-vue parser.
  class Emitter
    def initialize(memory, instructions, show_result: false)
      @mem = memory
      @instructions = instructions
      @show_result = show_result
    end

    def emit
      lines = []

      lines << "// Generated by s4c (LLVM IR → SUBNEG4 compiler)"
      lines << ""

      # Collect all data labels referenced by code instructions
      referenced = collect_referenced_labels

      # Data section (only emit referenced entries)
      lines << "// === Data Section ==="
      @mem.data_entries.each do |label, value|
        next unless referenced.include?(label)
        if label == "__stack_SP"
          lines << "#{label}:&stack_top"
        elsif @mem.addr_of_refs[label]
          lines << "#{label}:&#{@mem.addr_of_refs[label]}"
        else
          lines << "#{label}:#{value}"
        end
      end
      lines << ""

      # Code section
      lines << "// === Code Section ==="
      pending_labels = []

      @instructions.each do |inst|
        case inst
        when Array
          type = inst[0]
          case type
          when :label
            name, comment = inst[1], inst[2]
            if name && !name.empty?
              pending_labels << name
            end
            lines << "// #{comment}" if comment && !comment.empty?
          when :data
            name, value, comment = inst[1], inst[2], inst[3]
            cmt = comment && !comment.empty? ? " // #{comment}" : ""
            lines << "#{name}:#{value}#{cmt}"
          when :comment
            lines << "// #{inst[1]}"
          when :addr_data
            # Data word with &label (address-of) as value
            name, label, comment = inst[1], inst[2], inst[3]
            cmt = comment && !comment.empty? ? " // #{comment}" : ""
            lines << "#{name}:&#{label}#{cmt}"
          when :return_jump
            # Self-modifying goto: cd:D_LABEL: A, B, C, 0
            _, a, b, c, d_label, comment = inst
            prefix = flush_labels(pending_labels)
            cmt = comment && !comment.empty? ? " // #{comment}" : ""
            lines << "#{prefix}#{a}, #{b}, #{c}, cd:#{d_label}:0#{cmt}"
          when :push_write
            # Self-modifying write: A, B, cc:C_LABEL:0, NEXT
            _, a, b, c_label, comment = inst
            prefix = flush_labels(pending_labels)
            cmt = comment && !comment.empty? ? " // #{comment}" : ""
            lines << "#{prefix}#{a}, #{b}, cc:#{c_label}:0, NEXT#{cmt}"
          when :pop_read
            # Self-modifying read: A, cb:B_LABEL:0, C, NEXT
            _, a, b_label, c, comment = inst
            prefix = flush_labels(pending_labels)
            cmt = comment && !comment.empty? ? " // #{comment}" : ""
            lines << "#{prefix}#{a}, cb:#{b_label}:0, #{c}, NEXT#{cmt}"
          when :indirect_subneg_b
            # Fused indirect load+cmp via B: A, cb:B_LABEL:0, C, D
            _, a, b_label, c, d, comment = inst
            prefix = flush_labels(pending_labels)
            cmt = comment && !comment.empty? ? " // #{comment}" : ""
            lines << "#{prefix}#{a}, cb:#{b_label}:0, #{c}, #{d}#{cmt}"
          when :indirect_subneg_a
            # Fused indirect load+cmp via A: ca:A_LABEL:0, B, C, D
            _, a_label, b, c, d, comment = inst
            prefix = flush_labels(pending_labels)
            cmt = comment && !comment.empty? ? " // #{comment}" : ""
            lines << "#{prefix}ca:#{a_label}:0, #{b}, #{c}, #{d}#{cmt}"
          end
        when Subneg4
          prefix = flush_labels(pending_labels)
          cmt = inst.comment && !inst.comment.empty? ? " // #{inst.comment}" : ""
          lines << "#{prefix}#{inst.a}, #{inst.b}, #{inst.c}, #{inst.d}#{cmt}"
        end
      end

      # Flush any remaining pending labels
      pending_labels.each do |l|
        lines << "#{l}:0"
      end

      # Find main's return value variable
      retval_label = @mem.data_entries.map(&:first).find { |l| l == "main___retval" }
      retval_label ||= @mem.data_entries.map(&:first).find { |l| l.end_with?("___retval") }
      if @show_result && retval_label
        lines << ""
        lines << ">>> Result: ${#{retval_label}()}"
      end

      # Stack allocation (if stack is used)
      sp_label = @mem.data_entries.map(&:first).find { |l| l == "__stack_SP" }
      if sp_label
        lines << ""
        lines << "// === Stack ==="
        lines << "\#{#{STACK_SIZE}, stack_bottom, stack_top}#"
      end

      lines.join("\n") + "\n"
    end

    STACK_SIZE = 4096

    private

    def flush_labels(pending_labels)
      return "" if pending_labels.empty?
      prefix = pending_labels.map { |l| "#{l}:" }.join
      pending_labels.clear
      prefix
    end

    # Scan all instructions to find which data labels are actually referenced
    def collect_referenced_labels
      refs = Set.new
      # Always keep retval, stack SP, addr_of targets, and array elements
      @mem.data_entries.each do |label, _|
        refs << label if label.include?('___retval') || label == '__stack_SP'
        # Array elements must stay in memory (accessed via computed offsets)
        refs << label if label.include?('_arr_')
        # Global array elements (pattern: global_NAME_N)
        refs << label if label.start_with?('global_')
        # Subroutine shared vars (mul, div, etc.)
        refs << label if label.start_with?('__')
      end
      @mem.addr_of_refs.each do |label, target|
        refs << label
        refs << target
      end

      @instructions.each do |inst|
        case inst
        when Subneg4
          [inst.a, inst.b, inst.c, inst.d].each { |v| refs << v if v.is_a?(String) }
        when Array
          type = inst[0]
          case type
          when :data, :addr_data
            refs << inst[1] if inst[1]  # the data label itself
            refs << inst[2] if inst[2].is_a?(String) # value/target label
          when :return_jump
            _, a, b, c, d_label, _ = inst
            [a, b, c, d_label].each { |v| refs << v if v.is_a?(String) }
          when :push_write
            _, a, b, c_label, _ = inst
            [a, b, c_label].each { |v| refs << v if v.is_a?(String) }
          when :pop_read
            _, a, b_label, c, _ = inst
            [a, b_label, c].each { |v| refs << v if v.is_a?(String) }
          when :indirect_subneg_b
            _, a, b_label, c, d, _ = inst
            [a, b_label, c, d].each { |v| refs << v if v.is_a?(String) }
          when :indirect_subneg_a
            _, a_label, b, c, d, _ = inst
            [a_label, b, c, d].each { |v| refs << v if v.is_a?(String) }
          end
        end
      end
      refs
    end
  end
end
