-1, SHARED_IN, SHARED_OUT
-1, SHARED_IN, SHARED_OUT
-1, SHARED_IN, SHARED_OUT
-1, SHARED_IN, SHARED_OUT
-1, SHARED_IN, SHARED_OUT
-1, SHARED_IN, SHARED_OUT
-1, SHARED_IN, SHARED_OUT


0, -1, -1, HALT

0: 0
-1: -1
